### ISSUE TITLE
port dome code to run prometheus instead of using processing OPC.pde?

### ISSUE THREAD

**Issue by mrgriscom** [shen-tian/prometheus#4]
This way we still get the anti-aliasing and direct pixel-drawing support from the dome.

Would need to replace DomeCoord with an interface, and implement WingCoord that represents the geometry of the butterfly wings. Pixels would likely know their XY location, but also their wing #, row #, etc., allowing for line art animations pretty easily.

**Comment by shen-tian** [comment]
**WingCoord**

This would be somewhat low level control of the wing, right? My feeling is this is a bit more of a specialist animation mode, where we would bypass most of the rest of the signal chain. But it wouldn't add much for video based animations.

**Anti-aliasing** 

Always nice.

**Comment by mrgriscom** [comment]
For WingCoord, yeah, I don't really have plans for how we'd use that kind of low-level control -- the purpose is really to just decouple from DomeCoord to enable using the rest of the lsdome stack. Though I think it will be useful for pixels to know which wing they're on?

**Comment by shen-tian** [comment]
Feels like a lot of complexity of lsdome lib was around DomeCoord. So if we are not going to make a lot of use of WingCoord, feels like it's not worth porting?

In terms of which wing, I'd thought #5 handles that?

i.e. we give a XY canvas, which #5 maps to one or two wings, but that it also handles sending out the two OPC streams.

**Comment by mrgriscom** [comment]
Most of that complexity was around doing the layout and triangular grid, though, so wouldn't have to be part of any porting.

The real purpose of the class is just to have an object that represents each physical pixel. That way the driver can iterate over each pixel object to generate that pixel's RGB and send to the right place. We're sampling both wings from one input canvas, so it makes sense to do all the sampling in one pass, then the pixels identify which wing they're a part of, so the Driver pipes them to the right OPC socket.

Also, since #5 requires an intermediate transform that maps wing/pixels in real-world space (meters) to screen pixel space, and the wings can be mapped differently, we need to know which wing the pixel belongs to while doing that mapping.

I'm thinking:

abstract class LEDPixel {
  // given N fadecandy servers, which one serves this pixel
  int getOpcChannel();
  // return this pixel's XY coord in meters
  double[] toXy();
}

DomePixel /* formerly DomeCoord */ extends LEDPixel {
  int getOpcChannel() { return 0; }
  double[] toXy() { /* complex triangle grid stuff */ }
}

WingPixel extends LEDPixel {
  int getOpcChannel() { return wingNum; }
  double[] toXy() { /* return XY loaded from generated output */ }
}

**Comment by mrgriscom** [comment]
done
