### ISSUE TITLE
Implement a translation layer for placing wings on rendering canvas.

### ISSUE THREAD

**Issue by mrgriscom** [shen-tian/prometheus#5]
The dome geometry was symmetrical, so there was really only one logical way to place it over the animation window. The wings are asymmetrical, and there are two of them, so it is likely we will want to be able to map the rendering canvas to the wings in different ways depending on what looks best for the content and how the wings are currently trimmed (i.e., whether you can only see one or both of them at once).

I imagine being able to tweak the xy centering, scaling, and rotation of one wing. Then also setting the 2nd wing relative to that wing, via:
- mirror output of 1st wing to 2nd wing exactly (this will reverse display on the 2nd wing)
- flip output of 1st wing horizontally on the canvas (so 2nd wing is aligned to opposite vertical edge)
- rotate 180 (so 2nd wing is nestled in opposite corner of screen)

Together this creates a transformation matrix mapping from wing XY space (in meters) to screen space in pixels.

**Comment by shen-tian** [comment]
So, in the signal chain, where does this sit? 

Feels like it takes a video stream, or equivalent (true?) and maps them to the two OPC streams that's essentially hardware level. 

If that's the intention, probably important that it's sufficiently decoupled from the source (i.e. recorded video/generated animations/Syphon/Video capture).

Does this exist as a library that animation source code can call? (i.e. the output module)

Or is it mostly meant to be used with something like SyphonOPC/Video->OPC player, where it takes a framebuffer, and maps that to the wings as desired?

How many processes are we talking about here.

**Comment by mrgriscom** [comment]
Current lsdome process is:
DomeAnimation - render a color for each pixel
-> XYAnimation - get xy for each pixel (+ subsamples) and render that
-> CanvasSketch (processing) or Screencast -> map abstract xy to animation window row,column to sample (each sketch defines its own transformation based on various 'fit to screen' parameters)
<- DomeAnimation sends pixel colors to OPC

Suggested process is:
DomeAnimation - render a color for each pixel
-> XYAnimation is invoked with a ViewportMapper - viewport mapper maps each pixel's (and subsamples's) real-world xy (in meters) to a screen xy
-> CanvasSketch (processing) or Screencast -> samples the screen xy from the viewport w/o further transformation
<- DomeAnimation sends pixel colors to OPC. since the dome owns the OPC object, it can maintain mutliple OPC instances (connected to different servers) and send to the correct one based on the WingCoords wing id (or add a channelId) to the parent abstract base class

So I see the viewport transform as mostly a static configuration for the life of the animation, not something animations would set or tweak on their own. Syphon/Processing/other screengrab isn't aware of it; they just see screen xy coordinates.

**Comment by shen-tian** [comment]
Main thing is that this is all in the same process as the source animation, and not part of some OPC in OPC out program?

**Comment by mrgriscom** [comment]
done
